<<<<<<< HEAD
// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24/11/2024, 7:58:39 p.m.
const configMerger = require("C:/Users/jonat/Programacion/rustlings-web/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");
=======
// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/24/2024, 8:56:46 PM
const configMerger = require("/home/wilovy/Dev/RustLangESP/rustlings-web/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");
>>>>>>> develop

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/wilovy/Dev/RustLangESP/rustlings-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/wilovy/Dev/RustLangESP/rustlings-web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/wilovy/Dev/RustLangESP/rustlings-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/wilovy/Dev/RustLangESP/rustlings-web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/wilovy/Dev/RustLangESP/rustlings-web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/wilovy/Dev/RustLangESP/rustlings-web/plugins/**/*.{js,ts,mjs}","/home/wilovy/Dev/RustLangESP/rustlings-web/composables/**/*.{js,ts,mjs}","/home/wilovy/Dev/RustLangESP/rustlings-web/utils/**/*.{js,ts,mjs}","/home/wilovy/Dev/RustLangESP/rustlings-web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/wilovy/Dev/RustLangESP/rustlings-web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/wilovy/Dev/RustLangESP/rustlings-web/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];cfg["content"]["files"]["17"] = "/home/wilovy/Dev/RustLangESP/rustlings-web/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
