// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 24/11/2024, 3:04:31 p.m.
const configMerger = require("C:/Users/jonat/Programacion/rustlings-web/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/jonat/Programacion/rustlings-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jonat/Programacion/rustlings-web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jonat/Programacion/rustlings-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jonat/Programacion/rustlings-web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jonat/Programacion/rustlings-web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jonat/Programacion/rustlings-web/plugins/**/*.{js,ts,mjs}","C:/Users/jonat/Programacion/rustlings-web/composables/**/*.{js,ts,mjs}","C:/Users/jonat/Programacion/rustlings-web/utils/**/*.{js,ts,mjs}","C:/Users/jonat/Programacion/rustlings-web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jonat/Programacion/rustlings-web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jonat/Programacion/rustlings-web/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];cfg["content"]["files"]["17"] = "C:/Users/jonat/Programacion/rustlings-web/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
