name: Deploy to production

env:
  PROJECT_NAME: rustlings

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - "package.json"
      - "tsconfig.json"
      - "nuxt.config.ts"
      - "tailwind.config.js"
      - "app.vue"
      - "components/**"
      - "content/**"
      - "public/**"
      - "layouts/**"
      - "server/**"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: NodeJS Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install Deps
        run: npm install

      - name: Build
        env:
          VITE_CLARITY_PROJECT_ID: ${{ secrets.VITE_CLARITY_PROJECT_ID }}
        run: npm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        env:
          VITE_CLARITY_PROJECT_ID: ${{ secrets.VITE_CLARITY_PROJECT_ID }}
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        with:
          wranglerVersion: "4.19.1"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          secrets: |
            VITE_CLARITY_PROJECT_ID
            GH_CLIENT_ID
            GH_CLIENT_SECRET
            SESSION_SECRET
