name: Deploy to production

env:
  PROJECT_NAME: rustlings

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - "package.json"
      - "tsconfig.json"
      - "nuxt.config.ts"
      - "tailwind.config.js"
      - "app.vue"
      - "components/**"
      - "content/**"
      - "public/**"
      - "layouts/**"
      - "server/**"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Deps
        run: npm install

      - name: Build
        run: npm run build --preset=cloudflare_pages

      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.PROJECT_NAME}}-dist
          path: ./dist/

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        # env:
          # YOUR_SECRET: ${{ secrets.YOUR_SECRET }}
          # YOUR_OTHER_SECRET: ${{ secrets.YOUR_OTHER_SECRET }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./.output --project-name "${{ env.PROJECT_NAME }}"
          # secrets: |
          #   YOUR_SECRET
          #   YOUR_OTHER_SECRET
